title: Embodying Empire
description: Datasets for Embodying the Empire Women Succession and Dynasty in the Third Century
repository: embodyingempire/dissertation
include:
  - 404.md
  - index.md
  - author.md
plugins:
  - jekyll-relative-links
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
source: ./pages
collections_dir: ./pages
includes_dir: _includes
remote_theme: mmistakes/minimal-mistakes

theme: jekyll-theme-minimal
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
